trigger:
  branches:
    include:
      - '*'

jobs:
  - template: azure-pipelines-template.yml
    parameters:
      name: macOS
      vmImage: macOS-latest
      arch: x64

  - template: azure-pipelines-template.yml
    parameters:
      name: Ubuntu
      vmImage: ubuntu-latest
      arch: x64

  - template: azure-pipelines-template.yml
    parameters:
      name: Windows
      vmImage: vs2017-win2016
      arch: x64
